version: '3'
services:
  homebridge:
    build: ./.image/homebridge
    restart: always
    network_mode: host
    volumes:
      - .docker-data:/var/lib/homebridge/
    logging:
      driver: json-file
      options:
        max-size: "10mb"
        max-file: "1"


