name: pre-commit

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    permissions:
      contents: write # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: write # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.34.1
        
      - uses: supplypike/setup-bin@v3
        with:
          uri: 'https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64'
          name: 'hadolint'
          versionSpec: v2.12.0

      - uses: pre-commit/action@v3.0.0
        with: 
          extra_args: --all-files
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v4

      - uses: pre-commit/action@v3.0.0
        with: 
          extra_args: --all-files
