name: pre-commit

on:
  pull_request:
  push:
    branches: [master]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: yq - portable yaml processor
        uses: mikefarah/yq@v4.34.1

      - uses: pre-commit/action@v3.0.0
        with: 
          extra_args: --all-files
        continue-on-error: true

      - uses: stefanzweifel/git-auto-commit-action@v4

      - uses: pre-commit/action@v3.0.0
        with: 
          extra_args: --all-files
